name: home_cleaning
description: "App Home Cleaning"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

  #---------- PACKAGES ----------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1

  # Icons
  iconsax_plus: ^1.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  

  #---------- ./ PACKAGES END ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #---------- LOCAL ASSETS ----------#

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/icons/tabs/
    - assets/images/on_boarding_images/

#---------- LOCAL FONTS ----------#
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
